<?php

/**
 * @file
 * Hooks and callback.
 */

/**
 * Implements hook_page_bottom().
 */
function ffw_ass_datalayer_page_bottom(array &$page_bottom) {
  if(\Drupal::routeMatch()->getRouteName() === 'entity.node.canonical') {
    $metadata = \Drupal::service('ffw_ass_datalayer.metadata')->getNodeMetadata();
    $build['ffw_ass_datalayer'] = [
      '#type' => 'html_tag',
      '#tag' => 'script',
      '#value' => 'window.dataLayer = window.dataLayer || []; window.dataLayer.push(' . json_encode($metadata, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_AMP | JSON_HEX_QUOT | JSON_UNESCAPED_UNICODE) . ');',
      '#cache' => [
        'contexts' => ['user'],
      ],
    ];
    $page_bottom['ffw_ass_datalayer'] = $build;
  }
}
